# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1124, 254)
        mainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/001.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 150, 581, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit.setReadOnly(False)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(0, 120, 291, 21))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.state = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.state.setObjectName("state")
        self.horizontalLayout_3.addWidget(self.state)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(300, 10, 61, 31))
        self.label_3.setObjectName("label_3")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 289, 119))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout.addWidget(self.checkBox)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox_2 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_2.setChecked(False)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout.addWidget(self.checkBox_2)
        self.groupBox_2 = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(0, 20, 191, 21))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.Metasrc = QtWidgets.QRadioButton(self.horizontalLayoutWidget_5)
        self.Metasrc.setChecked(True)
        self.Metasrc.setObjectName("Metasrc")
        self.horizontalLayout_6.addWidget(self.Metasrc)
        self.OPGG = QtWidgets.QRadioButton(self.horizontalLayoutWidget_5)
        self.OPGG.setObjectName("OPGG")
        self.horizontalLayout_6.addWidget(self.OPGG)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(0, 0, 191, 41))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.radioButton = QtWidgets.QRadioButton(self.horizontalLayoutWidget_4)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_5.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_4)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_5.addWidget(self.radioButton_2)
        self.horizontalLayout_4.addWidget(self.groupBox)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 2)
        self.dataBase = QtWidgets.QLabel(self.centralwidget)
        self.dataBase.setGeometry(QtCore.QRect(460, 190, 121, 16))
        self.dataBase.setObjectName("dataBase")
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(630, 10, 441, 80))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.itemIcon_1 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.itemIcon_1.setObjectName("itemIcon_1")
        self.horizontalLayout_7.addWidget(self.itemIcon_1)
        self.itemIcon_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.itemIcon_2.setObjectName("itemIcon_2")
        self.horizontalLayout_7.addWidget(self.itemIcon_2)
        self.itemIcon_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.itemIcon_3.setObjectName("itemIcon_3")
        self.horizontalLayout_7.addWidget(self.itemIcon_3)
        self.itemIcon_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.itemIcon_4.setObjectName("itemIcon_4")
        self.horizontalLayout_7.addWidget(self.itemIcon_4)
        self.itemIcon_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.itemIcon_5.setObjectName("itemIcon_5")
        self.horizontalLayout_7.addWidget(self.itemIcon_5)
        self.itemIcon_6 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.itemIcon_6.setObjectName("itemIcon_6")
        self.horizontalLayout_7.addWidget(self.itemIcon_6)
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(340, 10, 241, 139))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.champName = QtWidgets.QLabel(self.gridLayoutWidget)
        self.champName.setAlignment(QtCore.Qt.AlignCenter)
        self.champName.setObjectName("champName")
        self.gridLayout.addWidget(self.champName, 1, 0, 1, 1)
        self.champIcon = QtWidgets.QLabel(self.gridLayoutWidget)
        self.champIcon.setAlignment(QtCore.Qt.AlignCenter)
        self.champIcon.setObjectName("champIcon")
        self.gridLayout.addWidget(self.champIcon, 0, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.champTier = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.champTier.setFont(font)
        self.champTier.setStyleSheet("")
        self.champTier.setObjectName("champTier")
        self.verticalLayout_3.addWidget(self.champTier)
        self.champScore = QtWidgets.QLabel(self.gridLayoutWidget)
        self.champScore.setObjectName("champScore")
        self.verticalLayout_3.addWidget(self.champScore)
        self.champWinRate = QtWidgets.QLabel(self.gridLayoutWidget)
        self.champWinRate.setObjectName("champWinRate")
        self.verticalLayout_3.addWidget(self.champWinRate)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 1, 2, 1)
        self.gridLayout.setColumnStretch(0, 2)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setRowStretch(0, 3)
        self.gridLayout.setRowStretch(1, 1)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1124, 21))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)
        mainWindow.setTabOrder(self.checkBox, self.checkBox_2)
        mainWindow.setTabOrder(self.checkBox_2, self.Metasrc)
        mainWindow.setTabOrder(self.Metasrc, self.OPGG)
        mainWindow.setTabOrder(self.OPGG, self.radioButton)
        mainWindow.setTabOrder(self.radioButton, self.radioButton_2)
        mainWindow.setTabOrder(self.radioButton_2, self.lineEdit)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "我的LOL小工具"))
        self.label.setText(_translate("mainWindow", "LeagueClient路徑:"))
        self.lineEdit.setText(_translate("mainWindow", "客戶端啟動時會自動抓取(須以系統管理員身分執行)"))
        self.label_2.setText(_translate("mainWindow", "現在遊戲狀態:"))
        self.state.setText(_translate("mainWindow", "未啟動客戶端"))
        self.label_3.setText(_translate("mainWindow", "當前英雄:"))
        self.checkBox.setText(_translate("mainWindow", "自動接受配對"))
        self.checkBox_2.setText(_translate("mainWindow", "自動開啟攻略網站"))
        self.groupBox_2.setTitle(_translate("mainWindow", "攻略網站"))
        self.Metasrc.setText(_translate("mainWindow", "Metasrc"))
        self.OPGG.setText(_translate("mainWindow", "OP.GG"))
        self.radioButton.setText(_translate("mainWindow", "ARAM"))
        self.radioButton_2.setText(_translate("mainWindow", "5V5"))
        self.dataBase.setText(_translate("mainWindow", "資料庫版本:讀取中"))
        self.itemIcon_1.setText(_translate("mainWindow", "item1"))
        self.itemIcon_2.setText(_translate("mainWindow", "item2"))
        self.itemIcon_3.setText(_translate("mainWindow", "item3"))
        self.itemIcon_4.setText(_translate("mainWindow", "item4"))
        self.itemIcon_5.setText(_translate("mainWindow", "item5"))
        self.itemIcon_6.setText(_translate("mainWindow", "item6"))
        self.champName.setText(_translate("mainWindow", "None"))
        self.champIcon.setText(_translate("mainWindow", "champIcon"))
        self.champTier.setText(_translate("mainWindow", "Tier"))
        self.champScore.setText(_translate("mainWindow", "整體分數:"))
        self.champWinRate.setText(_translate("mainWindow", "英雄勝率:"))

import ico_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())

